name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Build Docker image
        run: docker build -t render-flask-app .

      - name: Download Render CLI
        run: |
          curl -L https://github.com/render/render-cli/releases/latest/download/render_linux_amd64 -o render
          chmod +x render

      - name: Deploy to Render.com
        run: |
          ./render --version
          ./render login --api-key ${{ secrets.RENDER_TOKEN }}
          ./render deploy --name render-flask-app --docker-image render-flask-app --env-file .env --service-id ${{ secrets.SERVICE_ID }}
