name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Build Docker image
        run: docker build -t render-flask-app .

      - name: Deploy to Render.com
        run: |
          curl -L https://github.com/render/render-cli/releases/latest/download/render_linux -o render
          chmod +x render
          ./render --version
          ./render login --github-token ${{ secrets.GITHUB_TOKEN }}
          ./render up --file Dockerfile --name render-flask-app --force